import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Layout } from "antd";
import { Content, Footer, Header } from "antd/es/layout/layout";
import Link from "next/link";
import style from "./page.module.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Task-Dinamo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AntdRegistry>
          <Layout style={{ minHeight: "100vh" }}>
            <Header>
              <h1 className={style.headerTitle}>
                <Link href={"/"}>Dinamo</Link>
              </h1>
            </Header>
            <Content style={{ padding: "20px" }}>{children}</Content>
            <Footer className={style.footer}>
              <div className={style.footerContent}>
                <p>© 2024 Dinamo. All Rights Reserved.</p>
                <div className={style.links}>
                  <a href="/privacy-policy">Privacy Policy</a>
                  <a href="/terms-of-service">Terms of Service</a>
                  <a href="/contact-us">Contact Us</a>
                </div>
              </div>
            </Footer>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
